### ISSUE TITLE
'Enter'+.c or .cpp or .java files

### ISSUE THREAD

**Issue by darkkond** [Tej12345/ubuntu_home_configs#1]
When I install plugins listed in the .vimrc file I touch .c (.java, .cpp) file then I put some text there and press Enter, nvim or vim freezes. After that I press Ctrl+C and see this:
"\" : "\ u\pumvisible() ? "\": "\ u\pumvisible() ? "\", etc.
If a file has .txt, .vim or .php format all seems to be OK.

**Comment by Tej12345** [comment]
Already fixed by remapping keys to:
```
 inoremap <silent><expr> <C-J>
       \ pumvisible() ? "\<C-n>" :
       \ <SID>check_back_space() ? "\<TAB>" :
       \ coc#refresh()
 inoremap <expr><C-K> pumvisible() ? "\<C-p>" : "\<C-h>"
 inoremap <expr> <TAB> pumvisible() ? "\<C-y>" : "\<tab>"
```
But it's more like a workaround, not an actual fix of the problem.
